### PR TITLE
Remove lsb_release and sudo

### PR DESCRIPTION
**Pull request by gesinn-it**
remove _lsb_release_ and _sudo_ that might not be available in all environments

### CODE REVIEW

**Comment by gesinn-it** [comment]
@nanasess can you please run the CI to see if something breaks

**Comment by gesinn-it** [comment]
Example, where we use your action: https://github.com/gesinn-it/IDProvider

**Comment by nanasess** [comment]
@gesinn-it Welcome to composer-installer-action, thanks for the feedback.
LGTM.

**Review by nanasess — APPROVED** [review]

**Comment by nanasess** [comment]
@gesinn-it 
Thanks you so much!, Fixed version has been released.
https://github.com/nanasess/composer-installer-action/releases/tag/v2.0.2

**Pull request merged**
